 const personList = [
    {
      img: "./photo/00-PowerCoders_62.jpg",
      name: "Sümeyra",
      eyecolor: "black",
      age: 25,
      hobbies: ["hiking", "cycling", "reading"],
    },
    {
      img: "./photo/01-PowerCoders_01.jpg",
      name: "Susanne",
      eyecolor: "green",
      age: 28,
      hobbies: ["hiking", "sport", "reading"],
    },
    {
      img: "./photo/03-PowerCoders_03.jpg",
      name: "Anastasia",
      eyecolor: "black",
      age: 28,
      hobbies: ["hiking", "cycling", "reading", "travel"],
    },
    {
      img: "./photo/04-PowerCoders_04.jpg",
      name: "Merve",
      eyecolor: "black",
      age: 28,
      hobbies: ["hiking", "cycling", "reading"],
    },
    {
      img: "./photo/06-PowerCoders_06.jpg",
      name: "Medhane",
      eyecolor: "black",
      age: 28,
      hobbies: ["hiking", "cycling", "reading"],
    },
    {
      img: "./photo/08-PowerCoders_08.jpg",
      name: "Sahin",
      eyecolor: "black",
      age: 28,
      hobbies: ["hiking", "cycling", "reading"],
    },
    {
      img: "./photo/10-PowerCoders_10.jpg",
      name: "Melek",
      eyecolor: "black",
      age: 28,
      hobbies: ["hiking", "cycling", "reading", "sports"],
    },
    {
        img: "./photo/12-PowerCoders_12.jpg",
        name: "Kingsley",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "travel"],
      },
      {
        img: "./photo/14-PowerCoders_14.jpg",
        name: "Hüseyin",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/16-PowerCoders_16.jpg",
        name: "Harun",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/19-PowerCoders_19.jpg",
        name: "Mustafa",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "travel"],
      },
      {
        img: "./photo/20-PowerCoders_20.jpg",
        name: "Mustafa",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading","music"],
      },
      {
        img: "./photo/22-PowerCoders_22.jpg",
        name: "Latif",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/24-PowerCoders_24.jpg",
        name: "ümit",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "sports"],
      },
      {
        img: "./photo/26-PowerCoders_26.jpg",
        name: "Anna",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/28-PowerCoders_28.jpg",
        name: "Erdogan",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "travel"],
      },
      {
        img: "./photo/31-PowerCoders_31.jpg",
        name: "Caner",
        eyecolor: "black",
        age: 31,
        hobbies: ["hiking", "cycling", "reading", "sports"],
      },
      {
        img: "./photo/33-PowerCoders_33.jpg",
        name: "Ivan",
        eyecolor: "black",
        age: 50,
        hobbies: ["hiking", "cycling", "reading","music"],
      },
      {
        img: "./photo/35-PowerCoders_35.jpg",
        name: "Tetiana",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "travel", "reading"],
      },
      {
        img: "./photo/38-PowerCoders_38.jpg",
        name: "Yilmaz",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "travel"],
      },
      {
        img: "./photo/39-PowerCoders_39.jpg",
        name: "Muhammed",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/41-PowerCoders_41.jpg",
        name: "Hamdi",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading", "sports"],
      },
      {
        img: "./photo/43-PowerCoders_43.jpg",
        name: "Densy",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/45-PowerCoders_45.jpg",
        name: "Mustafa",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading","music"],
      },
      {
        img: "./photo/47-PowerCoders_47.jpg",
        name: "ömer",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/48-PowerCoders_48.jpg",
        name: "Burak",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading","music"],
      },
      {
        img: "./photo/50-PowerCoders_50.jpg",
        name: "Ersel",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/52-PowerCoders_52.jpg",
        name: "Engin",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/53-PowerCoders_53.jpg",
        name: "Simon",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/55-PowerCoders_55.jpg",
        name: "Oana",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/57-PowerCoders_57.jpg",
        name: "Nesrin",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
      {
        img: "./photo/59-PowerCoders_59.jpg",
        name: "Slava",
        eyecolor: "black",
        age: 28,
        hobbies: ["hiking", "cycling", "reading"],
      },
  ];
  export{personList};